config.go
executionSchema was not being set on the config object and causing a nil pointer dereference
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15394fb]
goroutine 52 [running]:
github.com/movio/bramble.(*ExecutableSchema).UpdateSchema(0x0, 0xc000051700, 0x0, 0x0)
/Users/lucianj/code/bramble/execution.go:75 +0x9b
github.com/movio/bramble.(*Gateway).UpdateSchemas(0xc00027f0c0, 0x12a05f200)
/Users/lucianj/code/bramble/gateway.go:27 +0x97
created by github.com/movio/bramble.Main
/Users/lucianj/code/bramble/main.go:38 +0x470
```
=> set executionSchema on config init

format.go, merge.go, merge_fixtures_test.go, merge_test.go, validate.go, validate_test.go
- Go through the merging logic even when merging a single schema: even when using a single schema we need to go through the merging logic to avoid exposing the underlying special types and queries (Service and
node).
- Removed empty `Query` type from merged schema. If the schemas contain only the `service: Service!` query it means the resulting `Query` type will be empty and should thus be removed from the result.
- Check schema is still going to be valid after merge, i.e. after we've removed the special types from the schema.
=> Schema validation and merge fixes

merge.go, merge_test.go
Custom directives (e.g. gqlgen's `@goField` directive) are currently not removed from fields in the merged schema.
=> Clean custom directives on result schema's fields

execution_test.go, merge.go, merge_fixtures_test.go, validate.go
The idea with https://github.com/movio/bramble/pull/5 was to remove the `Query` type from the merged schema if it doesn't contain any non builtin type.
The reason for doing that was that having an empty `Query` type would generate an invalid schema when formatting using `gqlparser`. However, now the issue is that it broke introspection...
So went another route instead and chose to delete the `Query` type from the schema only in the (very) few places where we need to format the schema with an empty query type.
=> Fix schema introspection

execution.go, execution_test.go, plan.go, plan_test.go, schema.go
This adds support for `__typename` fields on namespace objects, e.g.:
```graphql
{
myNamespace {
__typename
}
}
```
As these fields are quite special (they are not attached to a specific service) and we are not guaranteed to actually query a single service (see above example), I added some new logic for "bramble only" fields.
So:
- In the planning: allocate these fields to a special `__bramble` service
- In the execution: use `executeBrambleStep` to execute that special step
=> Add support for `__typename` fields on namespace objects

client.go, config.go, docs/configuration.md, execution.go, execution_test.go, gateway_test.go, introspection.go
This allows you to specify in your initial config files a Client max-response-size for your GraphQL clients.
It will default to the old hard-coded value of 1MB (1024*1024)
=> Configure GQLClient max-response-size

.github/workflows/docker.yml
Fix the Docker image by building a static Bramble binary.
Fixes https://github.com/movio/bramble/issues/15
=> Fix docker build

execution_test.go, plan.go, plan_fixtures_test.go, plan_test.go
The id field was being included in the query even when not required, i.e. even when there is a single query step and the data is not going to be merged with another step.
And because in that case the result just gets forwarded as is, the field was not getting removed during formatting.
This fixes query planning to not add the id field when the data won't be merged, or in other words:
- The step is not a child step; AND
- The step doesn't have any child step
=> Fix id field being incorrectly added to some queries

execution.go, execution_test.go
When dealing with fragment spreads we usually want to pass the response from the client as is, because we don't necessarily know what type was matched. In order to do that we need to not unmarshal the response more than necessary.
So when merging results maps, unmarshal into a `map[string]json.RawMessage`  instead of `map[string]interface{}`, this way we recursively unmarshal only what's strictly necessary to do the merging.
=> Fix inline fragment merge

auth.go, auth_test.go
Sort fields when marshalling AllowedFields to ensure fields order is deterministic (Go maps order is random).
This will help when generating or displaying roles.
=> Sort fields when marshalling AllowedFields

auth.go, auth_test.go
Fixed an issue during schema filtering using permissions.
This issue only occurred when using interfaces referencing interfaces referencing object types.
=> Fix missing recursive call filterDefinition

client.go, execution.go, execution_test.go
This makes the handling of execution errors a little bit nicer:
- Forward error extensions
- Add the query info (selection set, service name, service URL) to the extensions instead of in the error message.
I think this will make error messages a lot more readable.
For example instead of having:
```json
errors": [
{
"message": "error while querying $SERVICE_URL with $SELECTION_SET: $ERROR",
}
]
```
We'll get
```json
errors": [
{
"message": "$ERROR",
"extensions": {
"serviceName": "$SERVICE_NAME",
"serviceUrl": "$SERVICE_URL",
"selectionSet": "$SELECTION_SET"
}
}
]
```
Not related but also fixed the schema getting filered too many times on each query.
=> Better handling of execution errors

docs/plugins.md, plugins/cors.go
Add `max-age` option to CORS plugin.
This indicates how long the result of the preflight request can be cached.
=> Add max-age option to CORS plugin

.github/workflows/docker.yml, .gitignore, client.go, config.go, execution.go, gateway_test.go, introspection.go, middleware.go, plugins/opentracing.go
Adds user agent in the format `Bramble/$version ($operation)` when performing queries. E.g when querying services for an updated schema we would see `Bramble/v1.16.0 (update)`.
=> Include user agent in downstream queries

README.md
go build command in README may need updating. 
looks to be introduced in #19
=> fix go build command in README

plugins/limits.go
Set the GraphQL client timeout when using the `limits` plugin.
This avoids hitting the default client timeout when there's still time for the request to finish.
=> Set GraphQL client timeout when using the limits plugin

docs/plugins.md, plugins/meta.go
With the Meta plugin, you can programmatically query Bramble's federation information. The typical use case for this plugin is to build tooling around Bramble (e.g. a schema explorer that show which service exposes each field).
=> Add the Meta plugin

docs/plugins.md, plugins/meta.go
In the first implementation of the Meta plugin, I forgot to make `BrambleService` a boundary type. This commit fixes this.
=> Meta plugin: make BrambleService a boundary type

format.go
Return an error instead of a panic when `fields.ForName` returns `nil`
=> Check for nil field definition

execution_test.go, format.go
When marshalling the result of a federated query that contained a fragment spread we would hit an error in the marshalling logic. 
The added tests show the conditions needed to trigger the problem but the gist is that the information needed to know when inside the context of a fragment spread was being thrown out. This caused the marshalling logic to look up type information on the interface and not the target type of the spread.
The fix for now is to intercept the call that flattens out fragments and preserve the `TypeCondition` of the fragment. Longer term we might want to consider a refactor of the `marshalResult` function
=> Preserve and use type information when marshalling fragment spreads

format.go
When marshalling the result from a single service the type that gets passed into `marshalResult` is already `json.RawMessage`. This was being caught by the default case and causing a second and unnecessary `json.Marshal` call. While not a big deal for most use cases this could be a noticeable overhead with large responses.
=> Don't remarshal already marshalled json

execution_test.go, format.go
The previous fix (https://github.com/movio/bramble/pull/58) would only preserve the type information of the outer fragment, and any inner fragments would incorrectly inherit the parent type. This corrects that and will set the right TypeCondition for inner fragment spreads.
Also converted the whitespace to tabs in the new tests for consistency.
=> Correctly set inner fragment TypeCondition when formatting nested fragment spreads

docs/getting-started.md
Go does not accept any protocol on package address. 
Fixed this error on installation in this commit `malformed import path "https:/github.com/movio/bramble/cmd/bramble": invalid char ':'`
=> DOC: fixed typo on installation url.

docs/plugins.md
The code looks for the `public_role` role.
https://github.com/movio/bramble/blob/b5a9e78402f436a6e975ccdc6bdaf60e223a1c30/plugins/auth_jwt.go#L117
But the docs claim it looks for the role `public`.
=> Fix documentation on jwt auth

config.go, config_test.go
Adapted from the changes suggested by @hsblhsn in #66 but I decided it was better to allow the newer config field to fully specify the listen addresses and fallback to just the port on the unspecified address if that was all that was provided.
=> Allow specifying the full listen address in config

go.mod, go.sum, plugins/auth_jwt.go, plugins/auth_jwt_test.go
Use github.com/golang-jwt/jwt/v4 as the replacement for vulnerable version of github.com/dgrijalva/jwt-go
=> Update jwt library

plan.go, plan_test.go
This fixes a bug with the notoriously tricky hint selections of abstract types. 
Here's a schema...
```graphql
type Apple @boundary {
id: ID!
name: String!
}
type Banana @boundary {
id: ID!
name: String!
}
union Fruit = Apple | Banana
type Query {
fruit: Fruit
}
```
Then here's a query:
```graphql
query {
fruit {
...on Apple { name }
}
}
```
This query works fine if the endpoint returns an `Apple`, but it fails if a `Banana` is returned:
```json
{
"errors": [
{
"message": "boundaryIDFromMap: 'id' or '_id' not found"
}
],
"data": null
}
```
Why does a `Banana` fail? It's because ID hint selections are only being added to _user-defined boundary fragments_, i.e: `Apple`. In the above selection, the user hasn't explicitly made a `Banana` selection, so there's no ID hint added for a banana. …
=> Fix: expand all possible abstract ids

plan.go, plan_fixtures_test.go, plan_test.go
As described in https://github.com/movio/bramble/issues/73, deeply-nested selection paths that transitioned between services were broken. This was a fairly significant issue.
While extracting selection sets, the `mergedWithExistingStep` check was [treating _all_ consolidated fields as leaf values](https://github.com/movio/bramble/compare/main...gmac:fix-child-step-merging?expand=1#diff-11ffedf6a81044546aa19c8009998208f5a7afec3cdff04ca4281117b5ec0da7L163). That means that when a composite field was encountered with its own nested selections, that entire selection set was merged into the current planning step without traversing its children to delegate them properly. This resulted in fields belonging to foreign services getting lumped into the present service selection, and the query …
=> Fix: fully traverse nested field selections while planning

plan_fixtures_test.go, plan_test.go
Fixes the inconsistent test failures introduced by #81. That PR tested selection sets generated from an unordered map enumeration; as such, the tests fail periodically when the unordered enumeration doesn't match the way the tests were written.
This introduces a new `CheckUnorderedRootFieldSelections` helper that accepts an array of selections and assures that they're each found within the planned result's root field, regardless of appearance order.
Resolves https://github.com/movio/bramble/issues/88.
=> Fix: spurious test failures caused by #81

execution.go, execution_test.go, introspection.go
As a part of normal operation, Bramble periodically polls its known services to fetch their latest schemas and update its own merged schema. Movio runs everything in k8s where services come and go frequently, however we'd been noticing occasional issues where the merged schema wasn't an accurate representation of the current available services. It turns out this was due to a couple of bugs in the handling of errors while refreshing service schemas.
The problem could manifest in two ways: 
**Services that are currently available are not able to be queried**
* Service A is available and queryable
* Service A goes down
* No other has changed and so merged schema is not rebuilt
* Service A is unavailable but still a part of the merged schema
**Services that have gone down and come back are …
=> Fix issue with schema getting out of sync after service error

.gitignore, plan.go, plan_test.go
Preemptively fixing the same issue described in https://github.com/movio/bramble/pull/81, but with `__typename`...
Given that the execution resolver uses `__typename` while assembling abstract types, we need to assure that a typename is always returned. However, the automated `__typename` hints are currently only added to _user-defined_ fragments, and those aren't guaranteed to be present when making abstract type selections (case of point: selecting base interface fields).
While I haven't actually made this scenario fail, I strongly suspect that it can be broken.
This adds `__typename` to all abstract types. In the event that the user doesn't make a fragment selection on an abstract, the selection will still request typename for resolution purposes.
=> Always add __typename to abstract types

docs/algorithms.md, execution_test.go, plan.go, plan_fixtures_test.go, plan_test.go, query_execution.go
This adds `_bramble_id` as a universal ID hint, which allows `id` to behave as a standard user-defined selection. This fixes the numerous ways to break federation with user-defined field aliases describe in https://github.com/movio/bramble/issues/90 and https://github.com/movio/bramble/issues/93.
Apologies for the large PR – the vast majority of it is test fixtures.
As described in https://github.com/movio/bramble/issues/90, there are many creative ways for user-defined queries to break Bramble federation ids using field aliases, for example:
```graphql
query {
shop1 {
products {
boo: id
name
}
}
}
```
While dynamic adjustments _can_ be made to the query planner to account for such aliases, a user-aliased id still ends up breaking in the execution resolver, per …
=> Fix: user-defined field aliases may break federation

execution_test.go, query_execution.go
Fixes a bug with the final filtering of non-distinct composite field selections, per https://github.com/movio/bramble/issues/87.
Multiple selection scopes applied to the same object selection were not getting combined in the final result, for example:
```graphql
query {
shop1 {
products {
id
}
products {
name
}
}
}
```
While this query properly _fetched_ all requested data from underlying services (i.e.: query planning worked as expected), the resulting data only included fields for the first distinct `products` selection scope:
```json
{
"data": {
"shop1": {
"products": [
{
"id": "gid://shopapp/Product/7"
// ack, no "name"
}
]
}
}
}
```
This adjusts `unionAndTrimSelectionSetRec`, where the mapping of "seenFields" was filtering all repeated selection names as though they were leaf values. …
=> Fix: merge composite scopes in final selection

execution_test.go, plan.go, plan_fixtures_test.go, plan_test.go, query_execution.go, server_test.go, testsrv/gadget_test_server.go, testsrv/gizmo_test_server.go
Following on from the work in #94. With that change in place there are certain aliases that are reserved for bramble's internal use, this changes the `__typename` alias to be `_bramble__typename`. 
**Rationale**
- create a pattern of reserved aliases starting with `_bramble`
- reduce the chance of someone wanting to genuinely use the `__typename` alias for different purposes being unable to do so
- because of the point above there should generally be no confusion about whether the client requested the `__typename` field or bramble injected it
As a side note, any bramble injected fields (that were also not explicitly requested) are automatically omitted from the final response. This is because the response formatting uses the client's selection set to decide what goes into the response. …
=> Use `_bramble__typename` alias for bramble injected __typename 

plan.go
Fixes some problems with namespace operations in the query planner, and simplifies the overall logic in the process.
```graphql
query {
boo: myNamespace {
product {
name
}
manufacturer {
name
}
}
}
```
* The namespace handler condition was demonstrably broken by field aliases: it [composed its insertion point](https://github.com/movio/bramble/pull/108/files#diff-11ffedf6a81044546aa19c8009998208f5a7afec3cdff04ca4281117b5ec0da7L143) using field `Name` rather than `Alias`. This issue is now fixed.
* The namespace condition could also corrupt the user's original selection because it modified fields directly rather than making copies. This was problematic because it modified the selection used to filter the final result, as described in https://github.com/movio/bramble/issues/106. This is also …
=> Fix: broken namespace aliases and mutable selections

merge.go, merge_test.go
As described in https://github.com/movio/bramble/issues/113, it's less than ideal that namespaces and interfaces are omitted from the `Locations` map, and therefore get [handled as error side-effects](https://github.com/movio/bramble/blob/main/plan.go#L140-L141):
```go
loc, err := ctx.Locations.URLFor(parentType, location, selection.Name)
// Errors are returned for unmapped namespace/interface locations
if err == nil && loc != location {
// ...
}
```
These missing locations bank on a not-obvious rule that they're not allowed to transition services, so can alway use their parent object's location. Ideally these known resources would simply route to known locations, and missing location errors would be treated as _actual_ errors.
This adds interfaces to the `Locations` map so they become a …
=> Refactor: interface selections have proper location

plugins/meta.go
The previous case statement wasn't actually exhaustive as it excluded `interface`.  Now if `kindToStr` gets an interface it'll return the correct string. The special case for `ast.InputObject` and `ast.Object` were kept for backwards compatibility.
=> Add handling of ast.Interface to kindToStr

docs/sharing-types.md, execution_test.go, merge.go, plan.go, plan_test.go, query_execution.go, validate.go, validate_test.go
As discussed in https://github.com/movio/bramble/issues/97#issuecomment-968905753, this reads the name of each boundary query argument from the schema rather than hard-coding the argument names as `id` and `ids`. Now a boundary query naming is freeform so long as the field conforms to the basic signature of input and return:
```graphql
getMyThings(thingIds: [ID!]!): [Thing]! @boundary
```
This is an important first step in allowing the federation key to be customized for the graph, per https://github.com/movio/bramble/issues/109.
=> Dynamic boundary argument

config.go, docs/README.md, docs/configuration.md, docs/federation.md, merge.go, merge_test.go, plan.go, plugins/meta.go, schema.go, validate.go, validate_test.go
Per https://github.com/movio/bramble/issues/109, it was a bit restrictive that Bramble mandated the name `id` as the only allowed graph key. This adds configuration to customize the package's `IdFieldName`, at which time a graph may specify its own universal boundary key name. Also updates related docs.
Resolves https://github.com/movio/bramble/issues/109.
=> Allow customization of the graph "id" field

docs/plugins.md, execution_test.go, plugins/limits.go
Currently, if the limits plugin is used and a service times out, a generic 504 error is returned.
For example, if you make a query that involves two services, where one is very slow.
```
query {
serviceA {
quickField
}
serviceB {
slowField
}
}
```
You will get  `HTTP/1.1 504 Gateway Timeout` or  `failed to serve query in time`
Instead of using `http.TimeoutHandler`, use the GraphQL client timeout that already exists and is set by the plugin.
This way the same query from above would return the results it has, fills the nullable fields in with nulls and bubble up the errors.
```
{
"errors": {
"message": "error during request: Post \"http://localhost:8092/query\": context deadline exceeded",
...
}
"data": {
"serviceA": "quick answer",
"serviceB": null
}
}
```
=> Improve Bramble timeout support

execution_test.go, query_execution.go
For fields that are nullable, it is possible that the merge algorithm will encounter some destinations that are `null`. It makes sense to skip those fields.
For example:
```graphql
type Gizmo {
id: ID!
details: GizmoDetails
}
type GizmoDetails {
creator: Person!
}
type Person @boundary {
id: ID!
}
type Query {
gizmos: [Gizmo!]!
}
````
```graphql
type Person @boundary {
id: ID!
name: String!
}
type Query {
person(id: ID!): Person @boundary
}
```
```graphql
query {
gizmos {
details {
creator {
name
}
}
}
}
```
with results like:
```json
{
"data": {
"gizmos": [
{
"id": "GIZMO1",
"details": {
"creator": {
"name": "Alice"
}
}
},
{
"id": "GIZMO2",
"details": null
}
]
}
}
```
The merge algorithm would have expected to be able to walk down the `details`, `creator` path on `GIZMO2`.
=> Handle nullable destinations in results merge of query execution

client.go, client_test.go, config.go
Currently there is no way to customize the underlying HTTPClient used by the GraphQLClient.
There are many different usecases where HTTPClient needs to be customzied like introducing circuit breakers or custom roundtrippers.
I would like to introduce a new option to set custom HTTPClient.
=> Add custom http client option to GraphQLClient

execution.go, plugin.go
This PR aims to resolve the first point of issue #125. 
Removed `ModifyExtensions` as it doesn't seem to be used.
=> Remove ModifyExtensions from plugin

go.mod, go.sum
Currently there is DoS vulnerability in `graphql-go` package. This has been fixed in the latest release `v1.3.0` of the package
I would like to upgrade the package to latest version in this PR.
[Link to vulnerability](https://github.com/graph-gophers/graphql-go/security/advisories/GHSA-mh3m-8c74-74xh)
=> Fixed DoS vulnerability in graphql-go package

instrumentation_test.go
Resolves issue #112 
Using the `Cleanup` hook to restore log to the original output
=> Restore log output after tests finish

README.md
Following Issue #136 , I just propose a quick README update to make it more explicit that unions can't be shared across services + a link to the FAQ to provide more details.
=> Improve "not currently supported" part of README.md

merge_fixtures_test.go
Schema composition can fail. If it does, it previously caused a panic through referencing a nil pointer.
In this case, it's better to return early.
I discovered this when experimenting with modifications to the schema composition logic, and instead of failing tests, I got the panic from the test helper.
=> handle failed schema composition in merge test helper

config.go
This is to get around a race condition with nodejs based servers who
have a default HTTP Keep-Alive of 5 seconds.
=> Increase default polling period to 10 seconds.

plan.go, plan_fixtures_test.go, plan_test.go
`extractSelectionSet` seems to fail if a service is unreachable; which could be caused by missing schema information.
=> Add nil pointer check for parent definition in extractSelectionSet

client.go, client_test.go, introspection.go
We've noticed errors like (`connection reset by peer` or `EOF`) when bramble polls certain services, most notably anything built on nodejs. After some investigation it turns out this is due to servers having a shorter `Keep-Alive` than bramble's http client, which can cause race conditions.
Our first attempt was to introduce some randomness to the polling period with jitter. While this helped we still ran into the errors above.
It seems the most bullet proof way to not have race conditions is to have the client's `Keep-Alive` be shorter than the servers. Given service polling is not a high throughput task, we decided it's easier to just disable it entirely for this task. The http client bramble uses to run queries against downstream services is untouched.
=> Remove service polling client keep alive

auth.go, auth_test.go
When filtering down a schema union sub types could get incorrectly
excluded from the final schema.
This occurs when the permissions do not specify AllowAll on the union
type but rather use field level permissions.
=> Correctly include subtypes of union in filtered schema.

go.mod, go.sum, plugins/request_id.go
Add a new plugin that allows a user of bramble to set a request id that will be passed down to downstream services it calls using the header `X-Request-Id`. If the plugin is enabled and the user has not set the header, bramble will generate a uuid to pass down.
=> Add request ID plugin

introspection.go
Add an operationName to the service polling query. Can be used if any downstream services want to filter out these requests from logging etc.
=> Add operationName to bramble service poll

introspection.go
Some downstream servers do not infer the operationName from the selection set and some do. Make the name explicit to make sure it's compatible with all downstream servers.
=> Set operationName explicitly when polling

execution.go, execution_test.go, query_execution.go
FIxes: #151 
There was an issue multiple top level named fragment spreads under an interface type were not being correctly eliminated during the merge and format stages of query execution.
The behaviour should be that for both inline and named fragment spreads, only the spread that matches the concrete type in the response is kept. This was working for inline spreads but not named spreads.
The problem was made a little harder to fix due to an existing problem with `evaluateSkipAndInclude` that would overwrite the `ObjectDefinition` for a `FragmentSpread` with the wrong value.
This PR fixes both issues.
=> Fix fragment spread elimination during result merge + format

execution.go, execution_test.go
Bramble currently panic when the data in the first entry of `executionResults` was marshalled from a json null. This is due to us ending up with a typed nil as our destination map that wasn't being caught. 
The PR ensures that the first destination map passed into the merge is never nil.
=> Ensure the destination map for merging is never nil

main.go
Use the [cloudflare recommended default timeouts](https://blog.cloudflare.com/exposing-go-on-the-internet/#timeouts) for `http.Server` as recommended by @aerfio in #161
This might be worth being configurable, especially if used in combination with the `max-response-time` of the limits plugin.
=> Use the default cloudflare recommended timeouts

plugins/limits.go
The `MaxResponseTime` field was misspelled as `MaxResponeTime`.
=> Use correct spelling in limits plugin

merge.go, merge_fixtures_test.go, merge_test.go
The `mergePossibleTypes` function when populating the types just used the value from one of the source trees instead of the merged type.
This would only be apparent once one type of an `interface` was a `@boundary` type, depending on the order the services were merged in the final merged schema could be missing fields from other services.
=> Populate PossibleTypes with merged type

execution.go, execution_helpers_test.go, execution_result.go, execution_result_test.go, execution_test.go, merge_test.go, plan.go, plan_test.go
I think there are two ways to fix this
a) a886f69b5fc7cd0dd2ab924e8477d21b61bb9d6a just assume if the _bramble_id is missing that it's not a boundary type
b) 2dcec5a23e7b3366c0bbc533ee90c2818f46b612 always ask for __typename and check the types before merging.
I'm not sure which one is the correct one.
=> Abstract type boundary federation

.dockerignore, Dockerfile, docker-compose.yaml, examples/gqlgen-service/Dockerfile, examples/graph-gophers-service/Dockerfile, examples/nodejs-service/Dockerfile
- Simplify the copying of go files into docker context when building the gateway
- Pin the example services to golang:1.17 and node:18
=> Update docker-compose setup

client.go, executable_schema.go, execution.go, execution_helpers_test.go, introspection.go
This is useful for tracing and metrics. Currently child queries are made with an empty `operationName`.
=> Propogate `operationName` to subqueries

execution.go, execution_test.go
When federated service response contains graphql error with provided "Path" the bramble override this with it own internal "path" and we lost this information. This pull request will fix it.
=> Pass through original graphql error path

docker-compose.yaml, docs/configuration.md, metrics.go
Serve the `net/http/pprof` endpoint on the metrics port.
=> Enable debug/pprof endpoint

client.go, execution.go, execution_helpers_test.go, execution_test.go, format.go, format_test.go
Instead of inlining variables into downstream queries, which failed when the serialisation of the value from json didn't match the graphql syntax (eg if the variable was a complex json type) filter the variables map to the values required by the downstream query.
This should enable the definition of things like a json scalar value without bramble interfering and generating a syntactically invalid query.
=> Pass variables downstream

main_test.go
Since tests can create log entries on the error level etc, it can look like tests have failed when it is expected output.
By default send `logrus` output to `io.Discard` unless `-test.v` is true
=> Run tests without output by default

execution_test.go, middleware.go
[`ioutil` has been deprecated](https://pkg.go.dev/io/ioutil) and equivalent methods are in the `io` package now.
=> Replace deprecated ioutil funcs with io

docs/README.md, docs/getting-started.md
- `-conf` is deprecated and while still accepted `-config` is the preferred flag
- remove unnecessary and incorrect port forwards from getting started example
=> Small docs updates

gateway.go
Add a `time.Sleep` call to make the initialisation of the gateway more robust. In `main()`,  `UpdateSchemas()` is called _before_ the initialisation of the private router, so plugins have no chance to respond to schema update requests on the first try.
=> Add sleep in Gateway.UpdateSchema

executable_schema.go
The counter being reset every single time the schema was updated caused the metric to virtually be unscrapable. Every reset throws away the existing values. If prometheus has a larger scrape interval than bramble's schema update you will lose most of the counter's data.
=> Remove incorrect prometheus counter reset.

Dockerfile
This PR adds a label to the Docker images you provide to Github container registry, in order to get the Docker images linked on the project page on Github.
Further reads:
- [Github docs regarding labeling](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images)
- Actually got this hint from this [blog post](https://blog.codecentric.de/github-container-registry)
=> Link Docker images on profile page

executable_schema.go, plugin.go
InterceptResponse is called after bramble has finished executing a request. It can be used to inspect and/or modify the response bramble will return.
Added to help with https://github.com/movio/bramble/issues/204
=> Add InterceptResponse to the Plugin interface

plugins/meta.go
Unreachable services haven't loaded a schema yet so the definition is nil, causing the meta plugins query to fail with a nil dereference panic.
=> Only return Fields, Types for Services with Schema

Dockerfile
This speeds up subsequent image build times when modifying the `Dockerfile`
=> Use cache mount for build tasks

executable_schema.go, metrics.go
Use counter for tracking number of failures and the gauge for current error states.
We were finding once the error state was triggered it could not be reset as the counter is intended to be used as an ever incrementing metric.
=> Split error update metrics into gauge and counter

Dockerfile, go.mod, go.sum
- Update go.mod version
- Update docker image build version
- Update to alpine 3.18 base image
- Remove setting `GO111MODULE` as it defaults to `on` now.
=> Update go to version 1.20

plugins/headers.go, plugins/headers_test.go
Headers listed in the `allowed-headers` field of the plugin config will be passed from the client request to downstream services. This allows passing information like `Authorization` headers or custom information.
```json
{
"plugins": [
{
"name": "headers",
"config": {
"allowed-headers": ["Authorization"],
}
}
]
}
```
Addresses #212 raised by @codedge.
=> Add a plugin to allow headers passthrough

plugins/auth_jwt.go
Clean up the lint warning for `auth_jwt.go`
=> Apply vet suggestion to error message

execution_result.go, execution_result_test.go
When a response included multiple implementations of an interface type but the query only asked for certain types in the fragment spread invalid json could be generated, as a loop around the serialisation function added in a comma but without any accompanying content.
For this example schema
```graphql
interface Gizmo {
id: ID!
name: String!
}
type Gadget implements Gizmo {
id: ID!
name: String!
owner: String!
}
type Tool implements Gizmo {
id: ID!
name: String!
category: String!
}
type Query {
gizmos: [Gizmo!]!
}
```
The query
```graphql
query Gizmo {
gizmos {
id
...GizmoDetails
}
}
fragment GizmoDetails on Gizmo {
... on Gadget {
name
owner
}
}
```
would end up with invalid JSON for the `Tool` `Gizmo` as it would write a `,` after the `id` field expecting to then go through the fragment …
=> Fix serialisation bug when a fragment spread was not exhaustive

execution_result.go, execution_result_test.go
The previous fix only handled cases where an empty fragment returned nothing after a field had already been written, if it was first and returned nothing the subsequent fields would write an invalid comma ahead of the `innerBody`.
As discussed in #215 we need to rewrite this in a more robust way without relying on string building but this should handle the bug for now.
=> Handle empty fragment spread being first in query

auth_test.go, execution_test.go, gateway_test.go, instrumentation_test.go, merge_fixtures_test.go, plan_fixtures_test.go, validate_test.go
- Make sure `t.Helper()` is called everywhere relevant
- Use `t.Cleanup()` to remove custom teardown code
- Move a setting change that was in a strange place to closer to the test function
=> Use testing helpers

Dockerfile
The `/go/pkg/mod` cache was not being referenced in the build step so the modules were being downloaded twice.
=> Use cache of packages in build step

client.go, metrics.go
This will provide a metric for knowing if downstream services are hitting the time limit (if set by the limits plugin) for a request.
=> Add a counter metric for service timeouts

executable_schema.go
- the comment was wrong
- two panic messages were identical in different paths, making it harder to identify which path was failing
=> Correct doc comment in mergeMaps

plugins/meta.go
If a service is unreachable the `Services` map could be unpopulated, so fetching the service name is not possible.
=> Prevent panic when Service struct is nil

config.go, config.json.example, config_test.go, main.go
These timeouts should be tuneable for users who don't want to limit downstream services to only accept fast responses.
Address #228 by providing the option to increase the write timeout.
@codedge can you give this a review and see if it addresses your issue, it wasn't able to be configured by the `limits` plugin as it's the `main` method that sets up the `http.Server` instances.
In the `config.json` you can either provide a `default-timeouts` map of `read`, `write` and `idle` keys that will be used for all the `http.Server` instances or override the defaults with `gateway-timeouts` and `private-timeouts` maps that only need to provide values differing from the defaults.
=> Add configuration options for net/http timeouts

executable_schema.go, go.mod, go.sum
When running bramble in a Lambda, the startup time is critical. This fetches the schema updates in parallel, which dramatically reduces the startup time.
=> Fetch schema updates in parallel

plugins/request_id.go
Without this we can't actually correlate back to a bramble request
=> Log out request ID when the plugin is enabled

executable_schema.go, instrumentation.go, instrumentation_test.go
- Remove duplicated timestamp in log line
- Stop rounding the timings map in the response, most of the values were being rounded to `0s`
=> Clean up some debug information

.github/workflows/go.yml
Instead of specifying the go version again, as it has been testing on 1.17 even though it was updated to 1.20 at v1.4.10
=> Use go.mod to define go version in Actions

config.go, executable_schema.go, introspection.go
We are using mTLS with custom certificates and need to override the default http transport. It looked like it was working by overwriting the `QueryHTTPClient` field on the config but noticed that it wasnt being respected when new services was instantiated.
=> Use custom http clients for downstream Services

auth.go, auth_test.go, execution_test.go
- Update the auth error messages to be simpler
- Log out at debug level when fields are disallowed to help debugging permissions issues
=> Improve auth error messages

.github/workflows/movio.yml
The internal Movio repositories need to be notified of changes to the public repository, however GitHub actions only allows the originating repository to dispatch events instead of the other way around.
This is the most minimal action I can create to trigger internal workflows.
=> Notify internal Movio repository of updates

executable_schema.go, execution_introspection_test.go
Resolves https://github.com/movio/bramble/issues/254
=> Provide defaultValue on input types in schema introspection

plugins/cors.go
Add support for the `Access-Control-Allow-Methods` and `Access-Control-Expose-Headers` settings on the CORS middleware.
=> Add config for more CORS middleware options

client.go
The npm module `graphql-http` is checking the Accept header and is looking for `utf8` in the charset instead of `utf-8`.
https://github.com/graphql/graphql-http/blob/v1.22.0/src/handler.ts#L593
JSON is almost always encoded in UTF-8 so we should be ok not specifying that.
I've raised an issue: https://github.com/graphql/graphql-http/issues/120
=> Remove charset from Accept header

merge.go
```
unused parameter: aTypes
unused parameter: bTypes
```
Remove the warning around some unused parameters and shorten the function a bit
=> Clean up unused arguments warning

execution.go, plan.go
As each step is completed, inject some information into the step that aids in debugging step failures and timing.
The information is accessed on the result object when the below request header is sent: `X-Bramble-Debug: plan`
=> Inject execution debugging info into query plan

gateway.go, plugin.go
For example, this will allow you to implement: [Disabling introspection based on authentication](https://gqlgen.com/reference/introspection/#disabling-introspection-based-on-authentication)
```go
func (p *IntrospectionPlugin) SetupGatewayHandler(handler *handler.Server) {
handler.AroundOperations(
func(ctx context.Context, next graphql.OperationHandler) graphql.ResponseHandler {
if u := authentication.GetRequestUserFromCtx(ctx); u.IsAuthorized() {
graphql.GetOperationContext(ctx).DisableIntrospection = false
}
return next(ctx)
},
)
}
```
=> Add ability to expand gateway handler for plugins

gateway.go
As I mentioned in https://github.com/movio/bramble/issues/80#issuecomment-2137465210, one could not override default transports now.
With this small change, one could set up own transport, because first transport get's selected:
https://github.com/99designs/gqlgen/blob/fb67b709af4f0c5ba6eff8222c728b076a6eb09b/graphql/handler/server.go#L98
It will allow users, for example, to introduce batching with a bramble plugin, as I also mentioned in comment: https://github.com/movio/bramble/issues/80#issuecomment-2137465210.
=> Allow adding transports before defaults

execution_result.go, execution_result_test.go
Fix case when there is a nullable null value in array item:
```graphql
type Gizmo {
id: ID!
color: String!
}
type Query {
gizmos: [Gizmo]!
}
```
```json
{
"gizmos": [
{ "id": "GIZMO1", "color": "RED" },
null,
{ "id": "GIZMO2", "color": "GREEN" }
]
}
```
=> Stop bubble up of error on nullable list item

instrumentation.go, instrumentation_test.go, middleware.go
This is intended to help us differentiate requests in the logs based on the operation name. With custom filters we could use the fields on the event but automatic tools like DataDog appear to group on the `msg` key.
So a request will now log something like:
```json
{
"duration": "11.3045ms",
"level": "info",
"msg": "query:randomGizmo",
"operation.name": "randomGizmo",
"operation.type": "query",
"request.body": {
"operationName": "randomGizmo",
"query": "query randomGizmo($d: String!) {\n  a: randomGizmo {\n    id\n    delay(duration: $d)\n\t\trating\n\t\temail\n\t\tname\n  }\n  b: randomGizmo {\n    id\n    delay(duration: $d)\n\t\trating\n\t\temail\n\t\tname\n  }\n}",
"variables": {
"d": "5ms"
}
},
"request.content-type": "application/json",
"request.path": "/query",
"response.size": …
```
=> Include operation type and name in log message

go.mod, go.sum, plugins/auth_jwt.go, plugins/auth_jwt_test.go
v2 has long been unmaintained, the example plugin usage was simple enough to only be using one struct for loading JWKS which hasn't changed during the major version changes.
=> Upgrade go-jose to v4

.github/workflows/go.yml, client.go, docs/plugins.md, executable_schema.go, execution_result.go
- Remove an unneeded nil check
- Remove loop var aliasing prevention now go1.22 has the [loop semantics changed](https://tip.golang.org/doc/go1.22#language)
=> Small linting fixes

config.go, main.go
`slog.LevelVar` supports the `encoding.TextUnmarshaler` interface which `flag.TextVar` can use, instead of needing to make our own.
=> Use encoding.TextUnmarshaler to set loglevel

middleware.go
Add the `Request.RemoteAddr` to the request log, stripping off the port.
Closes #227
=> Log request remote ip in message
