.github/workflows/docker.yml
Dockerfile
docs/getting-started.md

Automatically publish the Docker image when a new version is tagged.

Add docker image GH action

---

auth.go
auth_test.go

Add helper functions to merge multiple sets of permissions together.
Although this won't be used directly in Bramble for now, it is useful for plugins dealing with role management.
For example, this can be used to generate permissions for a user with multiple roles.

Add MergePermissions and MergeAllowedFields functions

---

auth.go
auth_test.go
execution_test.go

When a type was referenced in the schema only via an interface it got filtered out of the schema when filtering the schema with permissions.
This PR makes it so that when a type is an interface we add all possible types to the result schema.

Do not filter out type when it is referenced only via an interface

---

auth.go
auth_test.go

When filtering the query, any fragment in the selection set was flattened, which can cause issues when dealing with interfaces or enums.
This change makes it so that fragment spreads and inline fragments are preserved (but still filtered).

Preserve fragments when filtering query

---

.github/workflows/docker.yml
client.go
config.go
gateway_test.go
introspection.go

Will allow custom builds to set and use the version

Make version public

---

config.json.example
docs/plugins.md
plugins/playground.go

Was going to do a demo of bramble but ran into a few issues getting it running locally. This seems to fix it (mostly around the playground plugin crashing the service)

Fixing a few setup issues

---

.github/workflows/go.yml
query_execution.go

Fix data race in query execution

---

query_execution.go

Removes an unnecessary mutex by using `sync/atomic` primitives. Thanks for the suggestion, @andyyu2004.

Replace mutex with atomic primitives

---

execution_test.go
query_execution.go

When executing a plan with a child step who's parent is itself a child step, there is a unique code path that manipulates the parent step's data and insertion point to make sense to the child.
Anything relying on `data` from [here](https://github.com/movio/bramble/blob/main/query_execution.go#L177) on actually need the non-null boundary results. This [error](https://github.com/movio/bramble/blob/c69e57f7495a624d51261ac893dfec7bbec03032/query_execution.go#L306) in particular will be triggered if the first entry in `data` is null. 
You need a plan with two levels of child steps, for example:
```
{
"RootSteps": [
{
"ServiceURL": "http://127.0.0.1:61895",
"ParentType": "Query",
"SelectionSet": "{ tastyGizmos { id _bramble_id: id } }",
"InsertionPoint": null,
"Then": [
{
"ServiceURL": …
```

Filter out null boundary results before calling nested child step

---

execution.go
main.go

- Include extra info in log message on startup
- Prefer `-config` over `-conf` as config argument

Small changes for Movio

---

config.go
execution.go
execution_test.go
gateway_test.go
server_test.go

Resolves the second point of issue #125

Allow bramble to be used as a library

---

execution_test.go
query_execution.go

When formatting the final response to be sent back to the user we need two pieces of data to help shape the JSON, this is: the merged downstream response data, and the request selection set. In the past we used the merged downstream response data as our guide to creating the final JSON response. However, this approach had lots of incompatibilities with fragments, especially fragments on abstract types. There is just not enough information in the merged response data to decide which fields should be non-null and which shouldn't when it comes to fragments.
We now instead use the request selection set to guide how the final JSON should look, which when combined with injected `__typename` data in the response, has enough information to correctly format the JSON. While the selection set …

Use non recursive algorithm to tidy up SelectionSet for response formatting

---

main.go

Discovered this helper function added in go.16

Use signal.NotifyContext

---

config.json.example

Fixed key in "config.json.example" to match source code (config.go)

---

.github/workflows/docker.yml

- Updated actions to latest versions
- Made steps mirror the examples order
- Added permissions
- Added labels to image push - I think this will include it on the packages page

Update image action to add labels

---

.github/workflows/go.yml

Update codecov action

---

.github/workflows/go.yml
Dockerfile

Add a few of the main labels specified by https://github.com/opencontainers/image-spec/blob/main/annotations.md

Add opencontainers.org metadata to image

---

.github/workflows/movio.yml

As well as a push to `main`, also notify Movio when a release is published.

Notify Movio on release event

---

.github/workflows/docker.yml
.github/workflows/go.yml

Update to actions/checkout@v5 as this uses the node v20 runtime.

Update github actions

---

.github/workflows/docker.yml

Update action inputs to follow the recommended settings from the docs

Update image push action to latest actions

---

CODEOWNERS

Change code owners to reference everyone in @movio/backend.

Change the code owners to the backend team

---

docker-compose.yaml
examples/gqlgen-multipart-file-upload-service/Dockerfile
examples/gqlgen-service/Dockerfile
examples/graph-gophers-service/Dockerfile
examples/slow-service/Dockerfile

- Use json format `CMD`
- Remove `version` field from compose file

Improve docker usage

---

examples/bramble-examples.postman_collection.json

Examples calling `randomGizmo` and `uploadGizmoFile`

Add a Postman collection of example requests
